AllCops:
  TargetRubyVersion: 2.6

Style/YodaCondition:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Layout/SpaceAfterColon:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false